### PR TITLE
Add remove methods

### PR DESCRIPTION
**Pull request by MPur**
Add has and remove methods to use Config easier
Add tests for method has and method remove
Add .idea to .gitignore for phpstorm's users

### CODE REVIEW

**Comment by hassankhan** [comment]
Hi, thanks for the pull request.

Personally I wouldn't add a `remove()` method, [we've discussed this in the past](https://github.com/noodlehaus/config/issues/10) and don't think it's within this library's scope.

That said, the `has()` method seems useful, thoughts @noodlehaus @DavidePastore?

**Comment by MPur** [comment]
I understand. For me, it's like offsetUnset of ArrayAccess.
What do you think If I change remove and i call it forget for example ?

**Comment by hassankhan** [comment]
To be completely honest, the only reason we have `offsetUnset` is so we can use `ArrayAccess`, changing the method name isn't the problem, it's just that we don't want to introduce that functionality at all for simplicity's sake.

Obviously if more people want this, then there's no problem :+1:

**Comment by DavidePastore** [comment]
I agree with @hassankhan, I never had the need of the remove method. `has` could be really helpful.

**Comment by MPur** [comment]
Ok, I update and remove remove method.

**Comment by hassankhan** [comment]
Thanks for the PR!

**Pull request merged**
