### PR TITLE
Added merge support

### PR DESCRIPTION
**Pull request by raffis**
Possibility to merge ConfigInterface instances... which is quite needed if you need one configuration first, doing some stuff and then load other configurations.

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @raffis! Thanks for your PR. Can you please create another one pointing on **develop** branch?

**Comment by raffis** [comment]
@DavidePastore Sure, I switched the base in this PR, guess this should do the job. Or do you want me to create a new one?

**Review by hassankhan — APPROVED** [review]

**Comment by hassankhan** [comment]
Just had a look over the changes, LGTM from my side 👍 Thanks for the PR, @raffis!

**Comment by DavidePastore** [comment]
Thanks for your PR, @raffis.

**Pull request merged**
