### PR TITLE
Drop support for the end of life PHP versions

### LINKED ISSUE #144: Drop support for the end of life PHP versions
PHP 5.x, 7.0, 7.1, 7.2, and 7.3 reached their end of life and are no longer supported. I suggest the minimum requirement for the project should be raised to PHP 7.4 at least.

If you agree, I'm happy to work on a PR.

### PR DESCRIPTION
**Pull request by nbayramberdiyev**
Closes #144

### CODE REVIEW

**Review by DavidePastore — COMMENTED** [review]
Hi @nbayramberdiyev. Thanks for this! Could you please also remove the `yoast/phpunit-polyfills` dependency and its usages? It was used only to ensure that the PHP tests are executable also on old PHP Unit versions.

**Review by DavidePastore — CHANGES_REQUESTED** [review]
Take a look at the following comment: https://github.com/hassankhan/config/pull/149#pullrequestreview-929705410

**Comment by nbayramberdiyev** [comment]
Done in [`2db7c02`](https://github.com/hassankhan/config/pull/149/commits/2db7c02d90e37ba44df14bc0d8a7e98597d71113).

**Review by DavidePastore — APPROVED** [review]

**Comment by DavidePastore** [comment]
Thanks for your effort on this PR, @nbayramberdiyev.

**Pull request merged**
