### PR TITLE
Fix fatal error when root is null in has() method

### LINKED ISSUE #159: testing nested key `->has` on unmatched structure
Assuming a config like 
`{"foo": "bar"}`
Testing 
`$config->has('foo.bar.baz')` 
will throw `PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in /.../vendor/hassankhan/config/src/AbstractConfig.php:127`

A simple fix to make `has()` return expected `false` in this case could be to add `is_array($root) && ..` before running the `array_key_exists($segment, $root)` statement

### PR DESCRIPTION
**Pull request by omniError**
fixes #159

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @omniError. Thanks for your PR. Could you please also include some additional tests for it?

**Comment by omniError** [comment]
~~Just eyeballing it, it looks like this test should already cover this scenario:~~
https://github.com/hassankhan/config/blob/develop/tests/AbstractConfigTest.php#L248

~~Something changed between PHP 7.4 and 8.1 to cause this. Not familiar with your CI so can't comment further.~~

Hold on let me dig deeper into this.

**Comment by omniError** [comment]
Modified test should now catch this. I think this is going to need to be a patch release for php8 compat. Don't know off the top of my head if this change happened in php 8.0 but it is certainly broken in 8.1.

**Comment by omniError** [comment]
@DavidePastore did you need anything else?

**Comment by DavidePastore** [comment]
Thanks for your PR, @omniError!

**Pull request merged**
