### PR TITLE
Slight constructor refactoring, using PHPUnit now too

### PR DESCRIPTION
**Pull request by hassankhan**
Hi there, loved your library, such a lightweight gem. Just thought I'd use PHPUnit for tests instead, and thinned out the constructor method a little :wink: 

I was also going to maybe modify it slightly so you could pass it an array directly to the constructor. I'll try and get the tests to 100% too :smile:

### CODE REVIEW

**Comment by noodlehaus** [comment]
Thank you very much for this pull, Hassan! This is really great :)

**Comment by hassankhan** [comment]
I'm glad you liked it!

**Comment by noodlehaus** [comment]
Especially the tests :) This will be a starting point for me to write tests as well :D

**Comment by hassankhan** [comment]
Haha awesome, I hope you find it okay with what I've done, there are some things I would have liked to do better, and there are a few test cases that haven't got tests yet. I might do another PR in a few minutes :wink:

**Pull request merged**
