### PR TITLE
Add array and dir support in the constructor.

### PR DESCRIPTION
**Pull request by DavidePastore**
Now the Config class accepts also:
- an array of files from which it gets all the keys using array_replace_recursive;
- a directory of files.

It refers to #18.

### CODE REVIEW

**Comment by hassankhan** [comment]
I really like it, if you could just do those little fixes I asked form I'm definitely :+1: nice job!

EDIT: Could you also update the readme to make it clear that each config file overwrites any values from the last?

**Comment by DavidePastore** [comment]
@hassankhan thanks for your suggestions. I removed the else clauses and that causes errors in test. I also added a note in README.md.

**Comment by hassankhan** [comment]
I actually meant refactor the code so it doesn't need `else` clauses, but no matter, I've done the necessary work [on my own fork](https://github.com/hassankhan/config/tree/develop). If it all looks good to @noodlehaus, I'm happy to merge into `master` and tag a release.

**Comment by noodlehaus** [comment]
@hassankhan you practically own this project :D but yes, i'm really all in on this. thanks David and Hassan :+1:

**Comment by hassankhan** [comment]
Haha thanks for saying so, still like to make sure you approve :smile:

**Comment by hassankhan** [comment]
All merged in #21

**Pull request closed without merging**
