### PR TITLE
PSR-2 compliance

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by hassankhan** [comment]
Are multiline trailing commas part of PSR-2?

**Comment by hannesvdvreken** [comment]
No, symfony cs, which exceeds psr-2. They allow for cleaner diffs when stuff gets added to the array. Once you start using them, you will not create arrays without them ;-)

**Comment by hassankhan** [comment]
I dunno ... I kinda think they're ugly :confused:

**Comment by hassankhan** [comment]
No reason to not merge it though :wink:

**Comment by hannesvdvreken** [comment]
:+1: I hope you make it to the league.

**Comment by hassankhan** [comment]
Thanks! Fingers crossed :smile:

**Pull request merged**
