### PR TITLE
  Proposal of returning Exception if configuration key not found

### PR DESCRIPTION
**Pull request by acidvertigo**

### CODE REVIEW

**Comment by hassankhan** [comment]
Just saw the typo fixes, looks good to me but still need to discuss whether this should be the default behaviour or not.

**Comment by DavidePastore** [comment]
I think that we could have some sort of configuration `array` for the `Config` so we can decide to throw an `Exception` or not. For example:

``` php
$conf = new Config('config.json', array(
  'strict' => true //By default it will be false
));
$keyNotFound = $conf['keyNotFound']; //Throw the exception
```

**Comment by hassankhan** [comment]
+1 on that, I also think that we should add a `getDefaultOptions()` to `Config` rather than `AbstractConfig`.

**Comment by ashnazg** [comment]
I'd argue against this concept.  The caller already has `has()` available for verifying the existence of the key... thus a `get()` call to a bad key is avoidable.  Further, `get()` allows for a default value to be returned if the key is not set.  These two avenues seem to cover the scenario well enough.  Allowing for `get()` to throw an exception makes the interface contract for `get()` more complex, because now its behavior won't necessarily match its signature.

**Comment by tomzx** [comment]
:+1: with @ashnazg, I think that a missing key shouldn't be considered an exception. Furthermore, it makes handling calls to `get()` require to be wrapped in a try/catch block.

**Comment by hassankhan** [comment]
Hmm, I had forgotten about the `has()` method - it does make this PR seem rather ... unnecessary. Going to close for now

**Pull request closed without merging**
